name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  isValidPHP:
    runs-on: [ubuntu-latest]
    name: Lint-PHP
    steps:
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.0
  phpcs:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      with:
        args: "PSR12"